Лабораторная №4
Programming-Classrooms/practicalworks-DmitriyFilenko pull request #1
Opened 2023-12-10 16:05 UTC by DmitriyFilenko

## Pull Request лабораторной работы №4

### Условие лабраторной работы
Индивидуальное задание № 4
Тема: МАТРИЦЫ

Вариант 13

При решении следующих задач использовать динамический массив. При необходимости заполнения массива предусмотреть два способа: ввод с клавиатуры и заполнение с помощью датчика случайных чисел. В последнем случае перед заполнением массива ввести границы интервала, которому должны принадлежать элементы массива. 
Вывести результаты расчетов. 

В целочисленной прямоугольной  матрице A(mxn) найти:
 номер первой из строк, содержащей хотя бы один нуль;
 координаты  всех ее седловых точек, если таковые имеются.

2023-12-10 16:39 UTC, AlexandrOsiptsov requested changes
Нет, Ферштаппен, давай на дополнительный круг

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +{
Отступ после включения модулей

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +		throw std::exception("Invalid parametre of matrix!");
К чему здесь `static_cast<>`?

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +}
Лучше сделать отдельную функцию выделения памяти. А для полной инициализации матрицы использовать две функции друг за другом в main

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +		throw std::exception("Invalid parametre of matrix!");
Смотри выше

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +void matrixInit(int32_t**& matrix, size_t& columns, size_t& rows)
К чему передавать матрицу по ссылке?

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +}
Такую функцию лучше называть чем-то типа `mtrxMemClear`

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +void sedlo(size_t columns, size_t rows, int32_t** matrix)
Что за седло?

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +				std::cout << "Saddle point found at (" << i << ", " << j << ") with value " << matrix[i][j] << '\n';
Выводы делаются в main. Если тебе нужно сохранить что-то для этих выводов (массивы например), то или передавай указатели на них, или возвращай

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +		throw std::exception("\nInvalid random left border!");
Опять же, `static_cast<>` здесь не нужен

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +void randFill(int32_t** matrix, size_t rows, size_t columns, int32_t& left, int32_t& right)
fill что? fillenko?
Указывай в названии что конкретно ты собираешься заполнять

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +void manFill(int32_t** matrix, size_t rows, size_t columns)
**Мужское** заполнение.
Пиши полностью - manual.

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +		break;
Скажем нет ненужной рекурсии. Опасно переполнением стека в данном случае

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +void matrixOut(int32_t** matrix, size_t rows, size_t columns)
принт

2023-12-10 16:39 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +}
Пустая строка

2023-12-10 16:42 UTC, DmitriyFilenko commented on laboratory-task-4/main.cpp
> +{
аа блин извини

2023-12-10 16:43 UTC, DmitriyFilenko commented on laboratory-task-4/main.cpp
> +		throw std::exception("Invalid parametre of matrix!");
проверяет на целое число. если размер не целый, то капут

2023-12-10 16:44 UTC, DmitriyFilenko commented on laboratory-task-4/main.cpp
> +}
не понял... ты имеешь в виду строки и столбцы отдельно?

2023-12-10 16:44 UTC, DmitriyFilenko commented on laboratory-task-4/main.cpp
> +void matrixInit(int32_t**& matrix, size_t& columns, size_t& rows)
по другому не работает. допер только таким способом, других пока не придумал

2023-12-10 16:45 UTC, DmitriyFilenko commented on laboratory-task-4/main.cpp
> +void randFill(int32_t** matrix, size_t rows, size_t columns, int32_t& left, int32_t& right)
XD щас будет

2023-12-10 16:45 UTC, DmitriyFilenko commented on laboratory-task-4/main.cpp
> +void manFill(int32_t** matrix, size_t rows, size_t columns)
хахаххаха блин щас сделаю

2023-12-10 16:45 UTC, DmitriyFilenko commented on laboratory-task-4/main.cpp
> +		break;
?

2023-12-10 16:46 UTC, DmitriyFilenko commented on laboratory-task-4/main.cpp
> +void matrixOut(int32_t** matrix, size_t rows, size_t columns)
ок

2023-12-10 16:46 UTC, DmitriyFilenko commented on laboratory-task-4/main.cpp
> +}
где?

2023-12-10 16:57 UTC, DmitriyFilenko commented on laboratory-task-4/main.cpp
> +		throw std::exception("\nInvalid random left border!");
не согласен. а как проверить на тип вводимого значения? просто сразу статик кастовать в интовое?

2023-12-10 17:16 UTC, DmitriyFilenko commented on laboratory-task-4/main.cpp
> +				std::cout << "Saddle point found at (" << i << ", " << j << ") with value " << matrix[i][j] << '\n';
Анна Викторовна говорила в отдельной функции делать(((

2024-01-12 06:54 UTC, DmitriyFilenko commented on laboratory-task-4/main.cpp
> +void matrixInit(int32_t**& matrix, size_t& columns, size_t& rows)
для изменения)

2024-06-17 16:19 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:26 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:41 UTC, merged