Лабораторная работа №5
Programming-Classrooms/practicalworks-DmitriyFilenko pull request #2
Opened 2023-12-10 16:17 UTC by DmitriyFilenko

## Pull Request лабораторной работы №5

### Условие лабораторной работы

Задание 5. Подпрограммы
Вариант 13
Вычислить значение определенного интеграла с аналитически заданной подынтегральной функцией с заданной точностью eps:
Г) по формуле трапеций;
Д) по формуле Симпсона (параболических трапеций)
Интегралы описаны в файле main.cpp
Математические формулы не поддерживаются в окне реквестов гитхаба(

2023-12-10 16:22 UTC, AlexandrOsiptsov requested changes
Названия аргументов. Если указаны пределы интегрирования, значит и называться они должны соответствующе, а не A и B. Если кол-во отрезков, значит кол-то отрезков, а не N

2023-12-10 16:22 UTC, AlexandrOsiptsov commented on laboratory-task-5/main.cpp
> +    printf("%10.7f", simpsonsRule(func3, a3, b3, n));
`printf()` - функция из C. Используй методы C++

2023-12-10 16:22 UTC, AlexandrOsiptsov commented on laboratory-task-5/main.cpp
> +    b3 = 7.0;  // Верхний предел интегрирования для третьего интеграла
`a` и `b` - это не названия.

2023-12-10 16:22 UTC, AlexandrOsiptsov commented on laboratory-task-5/main.cpp
> +double simpsonsRule(double (*func)(double), double a, double b, int n) {
`a` и `b` - это не названия

2023-12-10 16:22 UTC, AlexandrOsiptsov commented on laboratory-task-5/main.cpp
> +double simpsonsRule(double (*func)(double), double a, double b, int n) {
`n` - тоже

2023-12-10 16:22 UTC, AlexandrOsiptsov commented on laboratory-task-5/main.cpp
> +double trapezoidalRule(double (*func)(double), double a, double b, int n) {
Названия аргументов

2023-12-10 16:25 UTC, DmitriyFilenko commented on laboratory-task-5/main.cpp
> +    printf("%10.7f", simpsonsRule(func3, a3, b3, n));
принт позволяет нормально выводить до точности в 7 знаков после запятой. Посоветуй способ из плюсов, пожалуйста!

2023-12-10 16:25 UTC, DmitriyFilenko commented on laboratory-task-5/main.cpp
> +    b3 = 7.0;  // Верхний предел интегрирования для третьего интеграла
понял,сейчас исправлю

2023-12-10 16:25 UTC, DmitriyFilenko commented on laboratory-task-5/main.cpp
> +double simpsonsRule(double (*func)(double), double a, double b, int n) {
ок

2023-12-10 16:42 UTC, AlexandrOsiptsov requested changes

2023-12-10 16:42 UTC, AlexandrOsiptsov commented on laboratory-task-5/main.cpp
> +    printf("%10.7f", simpsonsRule(func3, thirdLowerBord, thirdUpperBord, dividings));
Выбрось отсюда вообще printf

2023-12-10 16:43 UTC, AlexandrOsiptsov commented on laboratory-task-5/main.cpp
> +    printf("%10.7f", simpsonsRule(func3, thirdLowerBord, thirdUpperBord, dividings));
Для точности вывода есть `iomanip`

2023-12-10 16:52 UTC, DmitriyFilenko commented on laboratory-task-5/main.cpp
> +    printf("%10.7f", simpsonsRule(func3, thirdLowerBord, thirdUpperBord, dividings));
О! спасибо!

2024-06-17 16:19 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:26 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:40 UTC, merged